config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  resources :teams, only: [:index, :show]
  resources :matches, only: [:index, :show]
  resources :bo_tournaments, only: [:index, :show]
  resources :tournaments, only: [:index, :show]
  resources :bos, only: [:index, :show]
  resources :games, only: [:index, :show]
  devise_for :users

  root 'tournaments#index'

  get 'match/:id/remove_screen_shot', to: 'matches#remove_screen_shot', as: 'remove_match_screen_shot'

  get 'teams/:id/add_user', to: 'teams#add_user', as: 'add_user_to_team'

  get 'teams/:id/delete_user', to: 'teams#delete_user', as: 'delete_user_from_team'

  get 'tournaments/:id_tournament/:id_team/enroll', to: 'tournaments#enroll', as: 'enroll_team_to_tournament'

  get 'tournaments/:id_tournament/:id_team/leave', to: 'tournaments#leave', as: 'leave_tournament'

end

app/models/bo.rb
class Bo < ActiveRecord::Base
  has_many :bo_tournaments
  has_many :tournaments, through: :bo_tournaments

  def name_with_phase
    "#{name} - #{phase}"
  end

  def to_s
    name_with_phase
  end
end

app/controllers/admin/bos_controller.rb
module Admin
  class BosController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Bo.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Bo.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/bos_controller.rb
class BosController < ApplicationController
  before_action :set_bo, only: [:show, :edit, :update, :destroy]

  # GET /bos
  # GET /bos.json
  def index
    @bos = Bo.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @bos, status: :ok }
    end
  end

  # GET /bos/1
  # GET /bos/1.json
  def show
    @bo = Bo.find(params[:id])
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @bo, status: :ok }
    end
  end

  # GET /bos/new
  def new
    @bo = Bo.new
  end

  # GET /bos/1/edit
  def edit
  end

  # POST /bos
  # POST /bos.json
  def create
    @bo = Bo.new(bo_params)

    respond_to do |format|
      if @bo.save
        format.html { redirect_to @bo, notice: 'Bo was successfully created.' }
        format.json { render :show, status: :created, location: @bo }
      else
        format.html { render :new }
        format.json { render json: @bo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bos/1
  # PATCH/PUT /bos/1.json
  def update
    respond_to do |format|
      if @bo.update(bo_params)
        format.html { redirect_to @bo, notice: 'Bo was successfully updated.' }
        format.json { render :show, status: :ok, location: @bo }
      else
        format.html { render :edit }
        format.json { render json: @bo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bos/1
  # DELETE /bos/1.json
  def destroy
    @bo.destroy
    respond_to do |format|
      format.html { redirect_to bos_url, notice: 'Bo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bo
      @bo = Bo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bo_params
      params.require(:bo).permit(:name, :phase)
    end
end

app/helpers/bos_helper.rb
module BosHelper
end

app/views/bos/_form.html.erb
<%= form_for(@bo) do |f| %>
  <% if @bo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bo.errors.count, "error") %> prohibited this bo from being saved:</h2>

      <ul>
      <% @bo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phase %><br>
    <%= f.text_field :phase %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bos/edit.html.erb
<h1>Editing Bo</h1>

<%= render 'form' %>

<%= link_to 'Show', @bo %> |
<%= link_to 'Back', bos_path %>

app/views/bos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phase</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bos.each do |bo| %>
      <tr>
        <td><%= bo.name %></td>
        <td><%= bo.phase %></td>
        <td><%= link_to 'Show', bo %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/bos/new.html.erb
<h1>New Bo</h1>

<%= render 'form' %>

<%= link_to 'Back', bos_path %>

app/views/bos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bo.name %>
</p>

<p>
  <strong>Phase:</strong>
  <%= @bo.phase %>
</p>

<%= link_to 'Edit', edit_bo_path(@bo) %> |
<%= link_to 'Back', bos_path %>