config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  resources :teams, only: [:index, :show]
  resources :matches, only: [:index, :show]
  resources :bo_tournaments, only: [:index, :show]
  resources :tournaments, only: [:index, :show]
  resources :bos, only: [:index, :show]
  resources :games, only: [:index, :show]
  devise_for :users

  root 'tournaments#index'

  get 'match/:id/remove_screen_shot', to: 'matches#remove_screen_shot', as: 'remove_match_screen_shot'

  get 'teams/:id/add_user', to: 'teams#add_user', as: 'add_user_to_team'

  get 'teams/:id/delete_user', to: 'teams#delete_user', as: 'delete_user_from_team'

  get 'tournaments/:id_tournament/:id_team/enroll', to: 'tournaments#enroll', as: 'enroll_team_to_tournament'

  get 'tournaments/:id_tournament/:id_team/leave', to: 'tournaments#leave', as: 'leave_tournament'

end

app/models/tournament.rb
class Tournament < ActiveRecord::Base
  belongs_to :game
  has_many :bo_tournaments
  has_many :bos, through: :bo_tournaments
  has_and_belongs_to_many :teams

  def name_with_game
    "#{name}"
  end

  def to_s
    name_with_game
  end
end

app/controllers/admin/tournaments_controller.rb
module Admin
  class TournamentsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Tournament.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Tournament.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :set_tournament, only: [:show, :edit, :update, :destroy]

  # GET /tournaments
  # GET /tournaments.json
  def index
    @tournaments = Tournament.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @tournaments, status: :ok }
    end
  end

  # GET /tournaments/1
  # GET /tournaments/1.json
  def show
    @tournaments = Tournament.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @tournaments, status: :ok }
    end
  end

  # GET /tournaments/new
  def new
    @tournament = Tournament.new
  end

  # GET /tournaments/1/edit
  def edit
  end

  # POST /tournaments
  # POST /tournaments.json
  def create
    @tournament = Tournament.new(tournament_params)

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to @tournament, notice: 'Tournament was successfully created.' }
        format.json { render :show, status: :created, location: @tournament }
      else
        format.html { render :new }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tournaments/1
  # PATCH/PUT /tournaments/1.json
  def update
    respond_to do |format|
      if @tournament.update(tournament_params)
        format.html { redirect_to @tournament, notice: 'Tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @tournament }
      else
        format.html { render :edit }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.json
  def destroy
    @tournament.destroy
    respond_to do |format|
      format.html { redirect_to tournaments_url, notice: 'Tournament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /tournaments/:id_tounament/:id_team/enroll
  # Join the tournament
  def enroll
    @tournament = Tournament.find(params[:id_tournament])
    @team       = Team.find(params[:id_team])
    # check if the user can enroll
    if current_user.teams.include?(@team) && !@tournament.teams.include?(@team)
      @tournament.teams << @team
      redirect_to @tournament, notice: 'Vous avez bien rejoint le tournoi'+ @tournament.name
    else
      redirect_to @tournament, notice: 'Vous n\'avez pas le droit de rejoindre le tournoi'+ @tournament.name
    end
  end

  # DELETE /tournaments/:id_tounament/:id_team/leave
  # Leave a tournament
  def leave
    @tournament = Tournament.find(params[:id_tournament])
    @team       = Team.find(params[:id_team])
    # check if the user can enroll
    if current_user.teams.include?(@team) && @tournament.teams.include?(@team) 
      @tournament.teams.delete(@team)
      redirect_to @tournament, notice: 'Vous avez bien quitté le tournoi'+ @tournament.name
    else
      redirect_to @tournament, notice: 'Vous n\'avez pas le droit de quitter le tournoi'+ @tournament.name
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tournament
      @tournament = Tournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tournament_params
      params.require(:tournament).permit(:name, :description, :game_id, :teams_limit, :signup_start, :signup_end, :check_in, :date, :mode)
    end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<%= form_for(@tournament) do |f| %>
  <% if @tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% @tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :game_id %><br>
    <%= f.collection_select(:game_id, Game.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :teams_limit %><br>
    <%= f.number_field :teams_limit %>
  </div>
  <div class="field">
    <%= f.label :signup_start %><br>
    <%= f.datetime_select :signup_start %>
  </div>
  <div class="field">
    <%= f.label :signup_end %><br>
    <%= f.datetime_select :signup_end %>
  </div>
  <div class="field">
    <%= f.label :check_in %><br>
    <%= f.datetime_select :check_in %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :mode %><br>
    <%= f.number_field :mode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tournaments/edit.html.erb
<h1>Editing Tournament</h1>

<%= render 'form' %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

app/views/tournaments/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="page-header">Liste des <strong>tournois</strong></h1>

    <% @tournaments.each do |tournament| %>
    <div class="row">
      <div class="col-md-2 col-sm-4">
        <img class="img-responsive" src="http://placehold.it/750x750" alt="<%= tournament.name %>" />
      </div>
      <div class="col-md-6 col-sm-8">
        <h2>
          <%= tournament.name %><br>
          <small><%= tournament.game.name %></small>
        </h2>
        <p class="text-justify">
          <%= truncate(tournament.description, :length => 250, :omission => '[...]') %>
        </p>
        <br />
        <%= link_to 'Détail du tournoi', tournament, class:"btn btn-primary btn-sm pull-right" %>
        <% if user_signed_in? && !current_user.teams.empty? %>
          <div class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-user glyphicon-left"></span> 
                S'insrire <span class="caret"></span>
              </a>
            <ul class="dropdown-menu">
              <% current_user.teams.each do |team| %>
                <% if !tournament.teams.include?(team) %>
                <li><%= link_to team.name, enroll_team_to_tournament_path(tournament.id, team.id) %></li>
                <% end %>
              </ul>
              <% end %>
          </div>
        <% end %>
      </div>
      <div class="col-md-4 col-sm-12">
        <table class="table">
          <tr>
            <th colspan="2">Inscriptions<i class="glyphicon glyphicon-check pull-right"></i></th>
          </tr>
          <tr>
            <td>Début : </td>
            <td><%= tournament.signup_start.strftime("%d/%m/%Y à %H:%M") %></td>
          </tr>
          <tr>
            <td>Clôture : </td>
            <td><%= tournament.signup_end.strftime("%d/%m/%Y à %H:%M") %></td>
          </tr>
          <tr>
            <th>Début du tournoi</td>
            <td><%= tournament.date.strftime("%d/%m/%Y à %H:%M") %></td>
          </tr>
        </table>
      </div>
    </div>
    <hr />
    <% end %>

  </div>
</div>

app/views/tournaments/new.html.erb
<h1>New Tournament</h1>

<%= render 'form' %>

<%= link_to 'Back', tournaments_path %>

app/views/tournaments/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="page-header">Tournoi <strong><%= @tournament.name %></strong></h1>

    <div class="row">
      <div class="col-md-2 col-sm-4">
        <img class="img-responsive" src="http://placehold.it/750x750" alt="<%= @tournament.name %>" />
      </div>
      <div class="col-md-4 col-sm-8">
        <p class="text-justify">
          <%= @tournament.description %>
        </p>
        <dl class="dl-horizontal">
          <dt>Jeu : </dt>
          <dd><%= @tournament.game %></dd>
          <dt>Nombre d'équipes : </dt>
          <dd><%= @tournament.teams_limit %></dd>
          <dt>Mode : </dt>
          <dd><%= @tournament.mode %></dd>
        </dl>
      </div>
      <div class="col-md-4 col-sm-12">
        <table class="table">
          <tr>
            <th colspan="2">Inscriptions<i class="glyphicon glyphicon-check pull-right"></i></th>
          </tr>
          <tr>
            <td>Début : </td>
            <td><%= @tournament.signup_start.strftime("%d/%m/%Y à %H:%M") %></td>
          </tr>
          <tr>
            <td>Clôture : </td>
            <td><%= @tournament.signup_end.strftime("%d/%m/%Y à %H:%M") %></td>
          </tr>
          <tr>
            <th>Début du tournoi</td>
            <td><%= @tournament.date.strftime("%d/%m/%Y à %H:%M") %></td>
          </tr>
        </table>
      </div>
      <div class="col-md-2 col-sm-12">
        Liste des équipes dans inscrites :
        <ul>
          <% @tournament.teams.each do |team| %>
            <li>
            <%= link_to team.name, team %>,
            <% if current_user.teams.include?(team) %>
              <%= link_to 'Quitter', leave_tournament_path(@tournament.id, team.id) %>
            <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>