config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  resources :teams, only: [:index, :show]
  resources :matches, only: [:index, :show]
  resources :bo_tournaments, only: [:index, :show]
  resources :tournaments, only: [:index, :show]
  resources :bos, only: [:index, :show]
  resources :games, only: [:index, :show]
  devise_for :users

  root 'tournaments#index'

  get 'match/:id/remove_screen_shot', to: 'matches#remove_screen_shot', as: 'remove_match_screen_shot'

  get 'teams/:id/add_user', to: 'teams#add_user', as: 'add_user_to_team'

  get 'teams/:id/delete_user', to: 'teams#delete_user', as: 'delete_user_from_team'

  get 'tournaments/:id_tournament/:id_team/enroll', to: 'tournaments#enroll', as: 'enroll_team_to_tournament'

  get 'tournaments/:id_tournament/:id_team/leave', to: 'tournaments#leave', as: 'leave_tournament'

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :tournament
  belongs_to :team1, class_name:'Team', foreign_key: 'team1_id'
  belongs_to :team2, class_name:'Team', foreign_key: 'team2_id'

  has_attached_file :screen_shot, styles: { medium: "300x300>", thumb: "100x100>" }
  # Validate attachment content type
	validates_attachment_content_type :screen_shot, content_type: /\Aimage\/.*\Z/
	# Validate filename
	validates_attachment_file_name :screen_shot, matches: [/png\Z/, /jpe?g\Z/]

  def name_result
    "#{team1}(#{score_team1}) vs #{team2}(#{score_team1})"
  end

  def to_s
  	name_result
  end
end

app/controllers/admin/matches_controller.rb
module Admin
  class MatchesController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Match.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Match.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @matches, status: :ok }
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @match = Match.find(params[:id])
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @match, status: :ok }
    end
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_screen_shot
    @match = Match.find(params[:id])
    @match.screen_shot = nil
    @match.save
    redirect_to @match, flash: { success: 'Screen shot removed.' }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:tournament_id, :map, :team1_id, :team2_id, :score_team1, :score_team2, :stream, :screen_shot)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>
  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tournament_id %><br>
    <%= f.collection_select(:tournament_id, Tournament.all, :id, :name_with_game) %>
  </div>
  <div class="field">
    <%= f.label :map %><br>
    <%= f.text_field :map %>
  </div>
  <div class="field">
    <%= f.label :team1 %><br>
    <%= f.collection_select(:team1_id, Team.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :team2 %><br>
    <%= f.collection_select(:team2_id, Team.all, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :score_team1 %><br>
    <%= f.number_field :score_team1 %>
  </div>
  <div class="field">
    <%= f.label :score_team2 %><br>
    <%= f.number_field :score_team2 %>
  </div>
  <div class="field">
    <%= f.label :stream %><br>
    <%= f.text_field :stream %>
  </div>
  <div class="field">
    <%= f.label :screen_shot %><br>
    <% if @match.screen_shot.exists? %>
    <p>
      <%= image_tag @match.screen_shot.url(:medium) %>
      <%= link_to 'Remove Screen shot', remove_match_screen_shot_path %>
    </p>
    <% end %>
    <%= f.file_field :screen_shot %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/matches/edit.html.erb
<h1>Editing Match</h1>

<%= render 'form' %>

<%= link_to 'Show', @match %> |
<%= link_to 'Back', matches_path %>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Matches</h1>

<table>
  <thead>
    <tr>
      <th>Tournament</th>
      <th>Map</th>
      <th>Team1</th>
      <th>Team2</th>
      <th>Score team1</th>
      <th>Score team2</th>
      <th>Stream</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.tournament_id %></td>
        <td><%= match.map %></td>
        <td><%= match.team1_id %></td>
        <td><%= match.team2_id %></td>
        <td><%= match.score_team1 %></td>
        <td><%= match.score_team2 %></td>
        <td><%= match.stream %></td>
        <td><%= link_to 'Show', match %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form' %>

<%= link_to 'Back', matches_path %>

app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tournament:</strong>
  <%= @match.tournament_id %>
</p>

<% if @match.screen_shot.exists? %>
  <p>
    <%= image_tag @match.screen_shot.url(:medium) %>
  </p>
<% end %>

<p>
  <strong>Map:</strong>
  <%= @match.map %>
</p>

<p>
  <strong>Team1:</strong>
  <%= @match.team1 %>
</p>

<p>
  <strong>Team2:</strong>
  <%= @match.team2 %>
</p>

<p>
  <strong>Score team1:</strong>
  <%= @match.score_team1 %>
</p>

<p>
  <strong>Score team2:</strong>
  <%= @match.score_team2 %>
</p>

<p>
  <strong>Stream:</strong>
  <%= @match.stream %>
</p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>