config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  resources :teams, only: [:index, :show]
  resources :matches, only: [:index, :show]
  resources :bo_tournaments, only: [:index, :show]
  resources :tournaments, only: [:index, :show]
  resources :bos, only: [:index, :show]
  resources :games, only: [:index, :show]
  devise_for :users

  root 'tournaments#index'

  get 'match/:id/remove_screen_shot', to: 'matches#remove_screen_shot', as: 'remove_match_screen_shot'

  get 'teams/:id/add_user', to: 'teams#add_user', as: 'add_user_to_team'

  get 'teams/:id/delete_user', to: 'teams#delete_user', as: 'delete_user_from_team'

  get 'tournaments/:id_tournament/:id_team/enroll', to: 'tournaments#enroll', as: 'enroll_team_to_tournament'

  get 'tournaments/:id_tournament/:id_team/leave', to: 'tournaments#leave', as: 'leave_tournament'

end

app/models/bo_tournament.rb
class BoTournament < ActiveRecord::Base
  belongs_to :bo
  belongs_to :tournament
end

app/controllers/admin/bo_tournaments_controller.rb
module Admin
  class BoTournamentsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = BoTournament.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   BoTournament.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/bo_tournaments_controller.rb
class BoTournamentsController < ApplicationController
  before_action :set_bo_tournament, only: [:show, :edit, :update, :destroy]

  # GET /bo_tournaments
  # GET /bo_tournaments.json
  def index
    @bo_tournaments = BoTournament.all
  end

  # GET /bo_tournaments/1
  # GET /bo_tournaments/1.json
  def show
  end

  # GET /bo_tournaments/new
  def new
    @bo_tournament = BoTournament.new
  end

  # GET /bo_tournaments/1/edit
  def edit
  end

  # POST /bo_tournaments
  # POST /bo_tournaments.json
  def create
    @bo_tournament = BoTournament.new(bo_tournament_params)

    respond_to do |format|
      if @bo_tournament.save
        format.html { redirect_to @bo_tournament, notice: 'Bo tournament was successfully created.' }
        format.json { render :show, status: :created, location: @bo_tournament }
      else
        format.html { render :new }
        format.json { render json: @bo_tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bo_tournaments/1
  # PATCH/PUT /bo_tournaments/1.json
  def update
    respond_to do |format|
      if @bo_tournament.update(bo_tournament_params)
        format.html { redirect_to @bo_tournament, notice: 'Bo tournament was successfully updated.' }
        format.json { render :show, status: :ok, location: @bo_tournament }
      else
        format.html { render :edit }
        format.json { render json: @bo_tournament.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bo_tournaments/1
  # DELETE /bo_tournaments/1.json
  def destroy
    @bo_tournament.destroy
    respond_to do |format|
      format.html { redirect_to bo_tournaments_url, notice: 'Bo tournament was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bo_tournament
      @bo_tournament = BoTournament.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bo_tournament_params
      params.require(:bo_tournament).permit(:bo_id, :tournament_id)
    end
end

app/helpers/bo_tournaments_helper.rb
module BoTournamentsHelper
end

app/views/bo_tournaments/_form.html.erb
<%= form_for(@bo_tournament) do |f| %>
  <% if @bo_tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bo_tournament.errors.count, "error") %> prohibited this bo_tournament from being saved:</h2>

      <ul>
      <% @bo_tournament.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bo_id %><br>
    <%= f.collection_select(:bo_id, Bo.all, :id, :name_with_phase) %>
  </div>
  <div class="field">
    <%= f.label :tournament_id %><br>
    <%= f.collection_select(:tournament_id, Tournament.all, :id, :name) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bo_tournaments/edit.html.erb
<h1>Editing Bo Tournament</h1>

<%= render 'form' %>

<%= link_to 'Show', @bo_tournament %> |
<%= link_to 'Back', bo_tournaments_path %>

app/views/bo_tournaments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bo Tournaments</h1>

<table>
  <thead>
    <tr>
      <th>Tournament</th>
      <th>Bo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bo_tournaments.each do |bo_tournament| %>
      <tr>
        <td><%= bo_tournament.tournament %></td>
        <td><%= bo_tournament.bo %></td>
        <td><%= link_to 'Show', bo_tournament %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/bo_tournaments/new.html.erb
<h1>New Bo Tournament</h1>

<%= render 'form' %>

<%= link_to 'Back', bo_tournaments_path %>

app/views/bo_tournaments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bo:</strong>
  <%= @bo_tournament.bo_id %>
</p>

<p>
  <strong>Tournament:</strong>
  <%= @bo_tournament.tournament_id %>
</p>

<%= link_to 'Edit', edit_bo_tournament_path(@bo_tournament) %> |
<%= link_to 'Back', bo_tournaments_path %>